<?php 

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://satnam.freshsales.io/api/leads");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"lead\":{\"first_name\":\"rohit\", \"last_name\":\"Saini\", \"mobile_number\":\"9468406070\", \"company\": {\"name\":\"Widgetz.io (sample)\"} }}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Authorization: Token token=2-JvELnb08IKgANJawbcbw";
$headers[] = "Cache-Control: no-cache";
$headers[] = "Content-Type: application/x-www-form-urlencoded";
$headers[] = "Postman-Token: e4fe06b4-5dc4-fa52-0a48-17254d0ef06c";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);



?>